version: '3.1'

services:
  app:
    build: .
    image: app
    ports:
      - 3000:3000
    links:
      - mongo:mongo
      - redis:redis
    networks:
      - nursinghome
    environment:
      - DATABASE_URI=mongodb://mongo:27017/nursinghome
      - REDIS_HOST=redis
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      nursinghome:
        aliases:
          - mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: nursinghome

  mongo-express:
    image: mongo-express:0.54
    container_name: nursinghome-mongoexpress
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: admin

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      nursinghome:
        aliases:
          - redis
    restart: always
    command: redis-server --requirepass admin   
    ports:
      - '6379:6379'

networks:
  nursinghome:
    driver: bridge
      